Document: gazebo
Title: Debian gazebo Manual
Author: <insert document author here>
Abstract: This manual describes what gazebo is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gazebo/gazebo.sgml.gz

Format: postscript
Files: /usr/share/doc/gazebo/gazebo.ps.gz

Format: text
Files: /usr/share/doc/gazebo/gazebo.text.gz

Format: HTML
Index: /usr/share/doc/gazebo/html/index.html
Files: /usr/share/doc/gazebo/html/*.html
